In [1]:
import tensorflow as tf
print(tf.__version__)

2.9.1


In [2]:
# Create a tensor from a constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Get the number of dimensions
scalar.ndim

0

In [4]:
# Create a vector as a constant
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
vector.ndim

1

In [6]:
#Create a metrix (metrix has more than one dimension)
matrix = tf.constant([[10,7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [7]:
another_matrix = tf.constant([[10.,7.],[7.,10.],[3.,6.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 3.,  6.]], dtype=float16)>

In [8]:
# Create a tensor
tensor = tf.constant([[[4,6,3],[3,7,9]],
                      [[4,6,3],[3,7,9]],
                      [[4,6,3],[3,7,9]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[4, 6, 3],
        [3, 7, 9]],

       [[4, 6, 3],
        [3, 7, 9]],

       [[4, 6, 3],
        [3, 7, 9]]])>

### Init tensor from numpy

In [9]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [10]:
tensor_A = tf.constant(numpy_A)
tensor_A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [11]:
tensor_B = tf.constant(numpy_A, shape=(2,3,4))
tensor_B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

### Get information from tensors

In [12]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
#print(f'Rank: {rank_4_tensor.shape}')
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [13]:
print("Size: ", tf.size(rank_4_tensor).numpy())
print("NDim: ", rank_4_tensor.ndim)
print("Shape: ", rank_4_tensor.shape)
print("Data type: ", rank_4_tensor.dtype)
print("Elements along 0 axis:", rank_4_tensor.shape[0])
print("Elements along last axis:", rank_4_tensor.shape[-1])

Size:  120
NDim:  4
Shape:  (2, 3, 4, 5)
Data type:  <dtype: 'float32'>
Elements along 0 axis: 2
Elements along last axis: 5


### Indexing tensors

In [14]:
# Get first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [15]:
# Add a new dimension to an existing tensor
rank_2_tensor = tf.constant([[3,7],[10,5]])
print("ndim: ", rank_2_tensor.ndim)

rank_3_tensor = rank_2_tensor[..., tf.newaxis] # tf.expand_dims is an alternative
print("ndim: ", rank_3_tensor.ndim)

ndim:  2
ndim:  3


### Manipulation of tensors

**Basic operations**
`+`,`-`,`*`,`/`

In [16]:
math_tensor = tf.constant([[10,7],[3,4]])
math_tensor, math_tensor + 10

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]])>)

In [17]:
math_tensor, math_tensor * 2

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 14],
        [ 6,  8]])>)

In [18]:
math_tensor, math_tensor - 10

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -6]])>)

In [19]:
# use a tensorflow function / advantage is to use the GPU
math_tensor, tf.add(math_tensor, 10)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]])>)

### Matrix multiplication (dot product)

* http://matrixmultiplication.xyz/
* https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [20]:
print(math_tensor)
tf.linalg.matmul(math_tensor, math_tensor), math_tensor * math_tensor

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  49],
        [  9,  16]])>)

In [21]:
# Python shortcut
math_tensor @ math_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

### Change the datatype of a tensor

In [22]:
tf.cast(math_tensor, dtype=tf.float16)

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  4.]], dtype=float16)>

### Aggregating tensors

In [23]:
# Get the absolute numbers
abs_tensor = tf.constant([-7,-5])
abs_tensor, tf.abs(abs_tensor)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-7, -5])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 5])>)

In [24]:
x = tf.constant([0., 0., 0., 0.])
y = tf.constant([-5., -2., 0., 3.])
tf.minimum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-5., -2.,  0.,  0.], dtype=float32)>

In [25]:
rand_tensor = tf.constant(np.random.randint(0,100, size=50))
tf.size(rand_tensor).numpy(), rand_tensor.shape, rand_tensor.ndim

(50, TensorShape([50]), 1)

In [26]:
tf.reduce_min(rand_tensor), tf.reduce_max(rand_tensor), tf.reduce_mean(rand_tensor), tf.reduce_sum(rand_tensor)

(<tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=98>,
 <tf.Tensor: shape=(), dtype=int32, numpy=50>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2500>)

In [37]:
# Find positional min and max
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
tf.argmax(F), F[tf.argmax(F)], tf.argmin(F), F[tf.argmin(F)]

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

### Squeezing a tensor

In [36]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=[1,1,1,1,50])
G_sq = tf.squeeze(G)
G.shape, G_sq.shape

(TensorShape([1, 1, 1, 1, 50]), TensorShape([50]))

### One hot encoding

In [46]:
some_list = [0,1,2,3,4,5]

tf.one_hot(some_list, depth=6, on_value="X", off_value="_")

<tf.Tensor: shape=(6, 6), dtype=string, numpy=
array([[b'X', b'_', b'_', b'_', b'_', b'_'],
       [b'_', b'X', b'_', b'_', b'_', b'_'],
       [b'_', b'_', b'X', b'_', b'_', b'_'],
       [b'_', b'_', b'_', b'X', b'_', b'_'],
       [b'_', b'_', b'_', b'_', b'X', b'_'],
       [b'_', b'_', b'_', b'_', b'_', b'X']], dtype=object)>