In [4]:
import tensorflow as tf
print(tf.__version__)

2.9.1


In [5]:
# Create a tensor from a constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
# Get the number of dimensions
scalar.ndim

0

In [7]:
# Create a vector as a constant
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [8]:
vector.ndim

1

In [9]:
#Create a metrix (metrix has more than one dimension)
matrix = tf.constant([[10,7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [10]:
another_matrix = tf.constant([[10.,7.],[7.,10.],[3.,6.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 3.,  6.]], dtype=float16)>

In [11]:
# Create a tensor
tensor = tf.constant([[[4,6,3],[3,7,9]],
                      [[4,6,3],[3,7,9]],
                      [[4,6,3],[3,7,9]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[4, 6, 3],
        [3, 7, 9]],

       [[4, 6, 3],
        [3, 7, 9]],

       [[4, 6, 3],
        [3, 7, 9]]])>