In [4]:
import tensorflow as tf
print(tf.__version__)

2.9.1


In [5]:
# Create a tensor from a constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
# Get the number of dimensions
scalar.ndim

0

In [7]:
# Create a vector as a constant
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [8]:
vector.ndim

1

In [9]:
#Create a metrix (metrix has more than one dimension)
matrix = tf.constant([[10,7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [10]:
another_matrix = tf.constant([[10.,7.],[7.,10.],[3.,6.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 3.,  6.]], dtype=float16)>

In [11]:
# Create a tensor
tensor = tf.constant([[[4,6,3],[3,7,9]],
                      [[4,6,3],[3,7,9]],
                      [[4,6,3],[3,7,9]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[4, 6, 3],
        [3, 7, 9]],

       [[4, 6, 3],
        [3, 7, 9]],

       [[4, 6, 3],
        [3, 7, 9]]])>

### Init tensor from numpy

In [15]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [16]:
tensor_A = tf.constant(numpy_A)
tensor_A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [18]:
tensor_B = tf.constant(numpy_A, shape=(2,3,4))
tensor_B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

### Get information from tensors

In [25]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
#print(f'Rank: {rank_4_tensor.shape}')
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
print("Size: ", tf.size(rank_4_tensor).numpy())
print("NDim: ", rank_4_tensor.ndim)
print("Shape: ", rank_4_tensor.shape)
print("Data type: ", rank_4_tensor.dtype)
print("Elements along 0 axis:", rank_4_tensor.shape[0])
print("Elements along last axis:", rank_4_tensor.shape[-1])

Size:  120
NDim:  4
Shape:  (2, 3, 4, 5)
Data type:  <dtype: 'float32'>
Elements along 0 axis: 2
Elements along last axis: 5


### Indexing tensors

In [34]:
# Get first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [38]:
# Add a new dimension to an existing tensor
rank_2_tensor = tf.constant([[3,7],[10,5]])
print("ndim: ", rank_2_tensor.ndim)

rank_3_tensor = rank_2_tensor[..., tf.newaxis] # tf.expand_dims is an alternative
print("ndim: ", rank_3_tensor.ndim)

ndim:  2
ndim:  3


### Manipulation of tensors